### ISSUE TITLE
I don't know how best to explain this but...

### ISSUE THREAD

**Issue by DestroyTargetNonBasicLand** [lennoxho/incremental_merge#1]
...it doesn't work :(
![Screenshot 2020-11-10 000337](https://user-images.githubusercontent.com/36361031/98610779-52181880-22e8-11eb-91ef-2a5717c39eb0.png)
Double checked everything and tried different inputs just to make sure, but it look likes the tool can't detect output png's in the work directory.

**Comment by lennoxho** [comment]
Hi!

I see you are running "continue" mode (with -c").
Was the initial run successful? 

Do you mind sharing
1) the contents of your work/ directory (just 'dir')
2) The config.json file under work/
3) the settings you used in veai.exe (a screenshot would be helpful)

One thing to note is the script checks every 60 seconds for the last file of the current batch.
Did you make sure to wait a few minutes for the script to wake up?

Also, I just committed some bug fixes for variable frame rate videos.

**Comment by DestroyTargetNonBasicLand** [comment]
After some tinkering and bit of hair pulling, I finally figured out what was going on.

You see, the reason why the script wasn't able to detect anything is because VEAI outputs all the png's into a subfolder inside the output directory. 
If it's of any importance, VEAI also names the subfolders depending on different factors; example: "<work directory>\test_2.25x_1920x1080_gcg-5_png".

So if you please sir, could you make it so the script tries to fetch png's inside subfolders of the work directory instead it's root? That'd be awesome, thanks!

...I also would like to report that I've been getting this error while inputting mkv files:

> Verifying configuration...
> Extracing input video metadata...
> Traceback (most recent call last):
>   File "**.**\incremental_merge.py", line 356, in <module>
>     durations = verify_input_and_get_durations(input_info, args)
>   File "**.**\incremental_merge.py", line 182, in verify_input_and_get_durations
>     assert len(input_info["tracks"]) == 3
> AssertionError

Fortunately, I was able to get around the issue by cleaning up any extra info (track names, file titles etc.) via MKVToolNix and saving the file as .mp4.

Nevertheless. Your script is  without a doubt an absolute MUST for people like me you who have a shortage of storage space, but still want the freedom to have control over their encoding process by editing in their ffmpeg arguments of choice. (I was able to encode with x265 along some extra params with no issues so far!)

So thanks heaps!!.. Much love!

**Comment by lennoxho** [comment]
Thanks for the kind words!

**You see, the reason why the script wasn't able to detect anything is because VEAI outputs all the png's into a subfolder inside the output directory.**
Oh yeah. One of the steps in *First Run* is to "Change output directory to \<work directory\>" from the GUI.

**Could you make it so the script tries to fetch png's inside subfolders of the work directory instead it's root?**
I would prefer not to replicate how veai constructs the subdirectory name 🤔. 
Just make sure to change the \<work directory\> on the GUI!

`assert len(input_info["tracks"]) == 3`
Ahh ok. My script makes the assumption that your video has 3 tracks: "general", "video" and "audio".
If you have multi-channel audio for example, then the assert will fire.

I'm a bit apprehensive to go down the rabbit hole of supporting all configurations - video formats are a mess! /rant

**Comment by lennoxho** [comment]
I guess a few more tips and background info:

1) The reason why this script is a daemon and not a do-it-all utility is because of this issue
https://community.topazlabs.com/t/video-enhance-ai-v1-6-1/16587/209

2) The reason why mkv is required to be the output format is because the ffmpeg concat demuxer sometimes, inexplicably, drop frames.

3) veai sometimes decides to drop frames at the end 🤔. If that happens to you, delete the config.json file and rerun with -f \<frame count\>

**Comment by DestroyTargetNonBasicLand** [comment]
**One of the steps in First Run is to "Change output directory to <work directory>" from the GUI.**
... I can't believe that I failed at the easiest part of the process while simultaneously being able to add my own ffmpeg parameters to the script.. :facepalm:

**I would prefer not to replicate how veai constructs the subdirectory name.**
It always starts with *"file name"* and ends with *png* for what it's worth. But I completely understand how tedious that would be if you had to do it the **hard** way.. No worries!

**My script makes the assumption that your video has 3 tracks: "general", "video" and "audio".**
Good to know. The mkv's in question are all imbedded with chapter and/or subtitle files that's why. I will make sure to only leave the video and audio tracks from now on then remux the rest later, thanks for the tip!

**The reason why this script is a daemon and not a do-it-all utility is because of this issue:**
That's not a bug, It's a feature! (hehe 😁)

Again, I can't express my gratitude enough to you for making this kick-ass script. Never liked how limiting veai's mp4 encoder was, even more so now that is started messing with the audio for some reason. 

You gave us freedom from cheap and sub-par standards, and for that I thank you.
